# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1180, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 60, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 20, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 90, 81, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(750, 30, 421, 571))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(112, 39, 91, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(262, 39, 91, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 100, 91, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView_2.setGeometry(QtCore.QRect(20, 150, 391, 351))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(90, 40, 21, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(240, 40, 21, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(80, 100, 51, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QtCore.QRect(320, 510, 75, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(240, 510, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(260, 100, 141, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(230, 100, 51, 16))
        self.label_7.setObjectName("label_7")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(160, 10, 571, 511))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 530, 251, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 30, 113, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 80, 113, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(60, 30, 21, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(60, 80, 21, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(130, 110, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(490, 530, 241, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(100, 40, 113, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_9.setGeometry(QtCore.QRect(130, 90, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(50, 40, 41, 20))
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 130, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 160, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 200, 91, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 230, 91, 21))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(30, 270, 81, 21))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 420, 81, 21))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(30, 330, 81, 21))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(10, 450, 81, 21))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(30, 490, 91, 21))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(20, 520, 101, 20))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(20, 550, 101, 21))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(30, 300, 81, 21))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(40, 590, 61, 21))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(40, 620, 71, 21))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(40, 650, 81, 21))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(10, 390, 81, 21))
        self.pushButton_23.setObjectName("pushButton_23")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(120, 390, 31, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(100, 390, 21, 21))
        self.label_8.setObjectName("label_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(120, 420, 31, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(100, 420, 21, 21))
        self.label_9.setObjectName("label_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(120, 450, 31, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(100, 450, 21, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(50, 360, 111, 21))
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1180, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.open_see_bmp_pic)
        self.pushButton.clicked.connect(MainWindow.open_see_gray_bmp)
        self.pushButton_3.clicked.connect(MainWindow.the_info_show)
        self.pushButton_4.clicked.connect(MainWindow.equal_zoom_out_click)
        self.pushButton_5.clicked.connect(MainWindow.equal_zoom_in_click)
        self.pushButton_6.clicked.connect(MainWindow.roll_the_img)
        self.pushButton_9.clicked.connect(MainWindow.roll_the_img_all)
        self.pushButton_7.clicked.connect(MainWindow.roll_the_img_anti)
        self.pushButton_8.clicked.connect(MainWindow.resize_the_img)
        self.pushButton_10.clicked.connect(MainWindow.probability_to_histogram)
        self.pushButton_11.clicked.connect(MainWindow.method_gdh)
        self.pushButton_12.clicked.connect(MainWindow.method_noise)
        self.pushButton_13.clicked.connect(MainWindow.gose_polish)
        self.pushButton_16.clicked.connect(MainWindow.SobelSharp)
        self.pushButton_17.clicked.connect(MainWindow.RobertSharp)
        self.pushButton_12.clicked.connect(MainWindow.method_noise)
        self.pushButton_19.clicked.connect(MainWindow.salt_pepper)
        self.pushButton_14.clicked.connect(MainWindow.gause_noise)
        self.pushButton_23.clicked.connect(MainWindow.median_filter)
        self.pushButton_15.clicked.connect(MainWindow.mean_filter)
        self.pushButton_18.clicked.connect(MainWindow.Cannysharp)
        self.pushButton_20.clicked.connect(MainWindow.global_th)
        self.pushButton_21.clicked.connect(MainWindow.adp_th)
        self.pushButton_22.clicked.connect(MainWindow.ots_th)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "显示灰度图"))
        self.pushButton_2.setText(_translate("MainWindow", "打开文件"))
        self.pushButton_3.setText(_translate("MainWindow", "显示图片信息"))
        self.groupBox.setTitle(_translate("MainWindow", "图像信息"))
        self.label.setText(_translate("MainWindow", "宽"))
        self.label_2.setText(_translate("MainWindow", "高"))
        self.label_3.setText(_translate("MainWindow", "字节"))
        self.pushButton_10.setText(_translate("MainWindow", "均衡化"))
        self.pushButton_11.setText(_translate("MainWindow", "规定化"))
        self.label_7.setText(_translate("MainWindow", "名称"))
        self.groupBox_2.setTitle(_translate("MainWindow", "非等比缩放"))
        self.label_4.setText(_translate("MainWindow", "宽"))
        self.label_5.setText(_translate("MainWindow", "高"))
        self.pushButton_8.setText(_translate("MainWindow", "缩放"))
        self.groupBox_3.setTitle(_translate("MainWindow", "旋转"))
        self.pushButton_9.setText(_translate("MainWindow", "旋转"))
        self.label_6.setText(_translate("MainWindow", "顺时针"))
        self.pushButton_4.setText(_translate("MainWindow", "等比放大"))
        self.pushButton_5.setText(_translate("MainWindow", "等比缩小"))
        self.pushButton_6.setText(_translate("MainWindow", "顺时针旋转90"))
        self.pushButton_7.setText(_translate("MainWindow", "逆时针旋转90"))
        self.pushButton_12.setText(_translate("MainWindow", "添加普通噪声"))
        self.pushButton_13.setText(_translate("MainWindow", "高斯滤波平滑"))
        self.pushButton_14.setText(_translate("MainWindow", "添加高斯噪声"))
        self.pushButton_15.setText(_translate("MainWindow", "均值滤波平滑"))
        self.pushButton_16.setText(_translate("MainWindow", "soble算子边缘"))
        self.pushButton_17.setText(_translate("MainWindow", "Robert 算子边缘"))
        self.pushButton_18.setText(_translate("MainWindow", "Canny 算子边缘"))
        self.pushButton_19.setText(_translate("MainWindow", "添加椒盐噪声"))
        self.pushButton_20.setText(_translate("MainWindow", "全局阈值"))
        self.pushButton_21.setText(_translate("MainWindow", "自适应阈值"))
        self.pushButton_22.setText(_translate("MainWindow", "otsus二值化"))
        self.pushButton_23.setText(_translate("MainWindow", "中值滤波平滑"))
        self.label_8.setText(_translate("MainWindow", "核："))
        self.label_9.setText(_translate("MainWindow", "核："))
        self.label_10.setText(_translate("MainWindow", "核："))
        self.label_11.setText(_translate("MainWindow", "(奇数且输入一个数）"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.action.setText(_translate("MainWindow", "打开图片"))
